# Generated by Django 5.0.3 on 2024-03-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jaihanuman_Purifiers', '0003_feedback_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='serivce',
            name='about',
            field=models.CharField(default='NULL', max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Name',
            field=models.CharField(max_length=30),
        ),
    ]
