# Generated by Django 5.0.3 on 2024-03-25 09:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jaihanuman_Purifiers', '0004_serivce_about_alter_feedback_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Phone', models.PositiveBigIntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.CharField(max_length=100)),
                ('Booking_date', models.DateField(default=django.utils.timezone.now)),
                ('Delivery_date', models.DateField(default='null')),
                ('Install_details', models.CharField(default='null', max_length=100)),
            ],
        ),
    ]
