# Generated by Django 5.0.3 on 2024-03-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jaihanuman_Purifiers', '0005_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Delivery_date',
            field=models.DateField(default='0000-00-00'),
        ),
    ]
